server {
    listen 8080;
    
    location /api/ {
        proxy_pass http://127.0.0.1:8001/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 50M;
    }

    location / {
        root /app/frontend/build;
        try_files $uri $uri/ /index.html;
    }
}
